### ISSUE TITLE
-

### ISSUE THREAD

**Issue by yrammos** [53js/react-jsonschema-form-validation#1]

**Comment by hugomallet** [comment]
Have you finally managed to run the example succesfully?

**Comment by yrammos** [comment]
@hugomallet, thank you! Yes, I did, which is why I deleted the issue in embarrassment (was trying to submit an invalid form, duh).

I'm now working to keep the submit button dynamically disabled until the form is valid. Wouldn't this be easier if the `data` prop exposed the `state.valid` of the `Form` component, in addition to its form data? Using refs for this purpose is not ideal… Happy to create a new issue for this, if you prefer.

**Comment by yrammos** [comment]
@hugomallet I think I got it, there's a Context already. False alarm, presumably. Sorry… (ReactJS newb here…)

**Comment by hugomallet** [comment]
Yes please create an other issue for this. I think there are already a couple ways to achieve this. I have not enough time right now to provide you with examples about this, I keep you posted in your next issue
