### ISSUE TITLE
Not getting useFormContext()

### ISSUE THREAD

**Issue by vcardins** [53js/react-jsonschema-form-validation#4]
Hi!!

I can get the context:

```javascript
import { Form, useFormContext } from 'react-jsonschema-form-validation';
const context = useFormContext()
```
context is always 

`undefined`

Any idea? I wonder if there is something related with webpack and default exports.

**Comment by hugomallet** [comment]
Hi,

useFormContext is a custom React Hook.
So you must use it within a functional react component (react 16.8+ required).

You can find more informations about hooks here : https://fr.reactjs.org/docs/hooks-intro.html

**Comment by vcardins** [comment]
What I actually meat was the I couldn't import `useFormContext `as a function, `useFormContext()` was returning `undefined`.

**Comment by hugomallet** [comment]
It's because useFormContext is a hook (not a "function") !

Try tro reproduce this example : https://github.com/53js/react-jsonschema-form-validation/blob/master/src/demo/context/SubmitIfValid.js
