### ISSUE TITLE
Missing arguments in onChange handler

### ISSUE THREAD

**Issue by SvitlanaZakharova** [53js/react-jsonschema-form-validation#9]
```
memoGetOnChangeHandler = memoize((onChange, handleFieldChange) => (event) => {
		if (onChange) {
			// Pass Form.handleFieldChange handler as extra parameter to the onChange handler
			onChange(event, handleFieldChange);
			return;
		}

		handleFieldChange(event);
	})
```
this is onChange handler from Field.js. It passes further only first argument 'event' from component, but e.g. react-select passes the second param https://react-select.com/props.

**Comment by francois06** [comment]
You can easily use react-select with react-jsonschema-form-validation : 
[codesandbox demo](https://codesandbox.io/s/ecstatic-hypatia-z5w18?file=/src/App.js)

You are free to provide a custom onChange props to your <Field>   
or you can wrap the onChange props in your Select do some custom stuff and call the default onChange :
```
 const formatValue = value => value;
  const handleChange = value => {
    const event = {
      target: {
        name,
        value: isMulti ? (value || []).map(formatValue) : formatValue(value)
      }
    };
    onChange(event); // onChange from <Form> 
  };
  return (
    <Select
      onChange={handleChange}
      options={options}
      isMulti
      formatValue={formatValue}
      value={value}
      {...props}
    />
```

We provided other examples here : 
[Demo with react-select](https://53js.github.io/react-jsonschema-form-validation/#/examples/react-select)
[Src](https://github.com/53js/react-jsonschema-form-validation/blob/master/src/demo/react-select/index.js)

**Comment by SvitlanaZakharova** [comment]
That works! Thanks.
